#ifndef GUARD_CONSTANTS_BATTLE_FACTORY_MONS_H
#define GUARD_CONSTANTS_BATTLE_FACTORY_MONS_H

#define BATTLE_FACTORY_MON_VENUSAUR     	1
#define BATTLE_FACTORY_MON_VENUSAUR_MEGA	2
#define BATTLE_FACTORY_MON_CHARIZARD		3
#define BATTLE_FACTORY_MON_CHARIZARD_MEGA_Y 4
#define BATTLE_FACTORY_MON_CHARIZARD_MEGA_X 5
#define BATTLE_FACTORY_MON_BLASTOISE		6
#define BATTLE_FACTORY_MON_BLASTOISE_MEGA	7

#define NUM_FALLARBOR_TENT_MONS         8
#endif  // GUARD_CONSTANTS_BATTLE_FACTORY_MONS_H