@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.globl	sDownArrowCounterAndYCoordIdx
	.section ewram_data,"aw"
	.type	 sDownArrowCounterAndYCoordIdx,object
	.size	 sDownArrowCounterAndYCoordIdx,8
sDownArrowCounterAndYCoordIdx:
	.space	8
	.globl	gGiftIsFromEReader
	.type	 gGiftIsFromEReader,object
	.size	 gGiftIsFromEReader,1
gGiftIsFromEReader:
	.byte	0x0
	.section .rodata
	.align	1, 0
	.type	 gUnkTextboxBorderPal,object
gUnkTextboxBorderPal:
	.short	0x4a52
	.short	0x7ef2
	.short	0x7f93
	.short	0x7ff9
	.short	0x79ac
	.short	0x56d4
	.short	0x6338
	.short	0x6f9b
	.short	0x7fff
	.short	0x0
	.short	0x0
	.short	0x0
	.short	0x318c
	.short	0x4a52
	.short	0x6318
	.short	0x0
	.size	 gUnkTextboxBorderPal,32
	.align	2, 0
	.type	 gUnkTextboxBorderGfx,object
gUnkTextboxBorderGfx:
	.word	0x10010
	.word	-0xfffffcd
	.word	0x22019001
	.word	-0x6ffe0fde
	.word	0x11113301
	.word	0x19001f0
	.word	0x1f04444
	.word	-0xf01fe70
	.word	-0xffe0f8f
	.word	-0xffe0fff
	.word	-0xffe0fff
	.word	0x1
	.size	 gUnkTextboxBorderGfx,48
	.align	2, 0
	.type	 sBGTemplates,object
	.size	 sBGTemplates,16
sBGTemplates:
	.byte	0xf8
	.byte	0x0
	.byte	0x0
	.space	1
	.byte	0xe1
	.byte	0x10
	.byte	0x0
	.space	1
	.byte	0xd2
	.byte	0x20
	.byte	0x0
	.space	1
	.byte	0xc3
	.byte	0x30
	.byte	0x0
	.space	1
	.align	2, 0
	.type	 sMainWindows,object
sMainWindows:
	.byte	0x0
	.byte	0x0
	.byte	0x0
	.byte	0x1e
	.byte	0x2
	.byte	0xc
	.short	0x13
	.byte	0x0
	.byte	0x1
	.byte	0xf
	.byte	0x1c
	.byte	0x4
	.byte	0xc
	.short	0x4f
	.byte	0x0
	.byte	0x0
	.byte	0xf
	.byte	0x1e
	.byte	0x5
	.byte	0xd
	.short	0x4f
	.byte	0xff
	.space	7
	.size	 sMainWindows,32
	.align	2, 0
	.type	 sWindowTemplate_PromptYesOrNo_Width28,object
	.size	 sWindowTemplate_PromptYesOrNo_Width28,8
sWindowTemplate_PromptYesOrNo_Width28:
	.byte	0x0
	.byte	0x1
	.byte	0xf
	.byte	0x1c
	.byte	0x4
	.byte	0xc
	.short	0xe5
	.align	2, 0
	.type	 sWindowTemplate_PromptYesOrNo_Width20,object
	.size	 sWindowTemplate_PromptYesOrNo_Width20,8
sWindowTemplate_PromptYesOrNo_Width20:
	.byte	0x0
	.byte	0x1
	.byte	0xf
	.byte	0x14
	.byte	0x4
	.byte	0xc
	.short	0xe5
	.align	2, 0
	.type	 sMysteryGiftMenuWindowTemplate,object
	.size	 sMysteryGiftMenuWindowTemplate,8
sMysteryGiftMenuWindowTemplate:
	.byte	0x0
	.byte	0x1
	.byte	0xf
	.byte	0x13
	.byte	0x4
	.byte	0xc
	.short	0xe5
	.align	2, 0
	.type	 sWindowTemplate_ThreeOptions,object
	.size	 sWindowTemplate_ThreeOptions,8
sWindowTemplate_ThreeOptions:
	.byte	0x0
	.byte	0x8
	.byte	0x6
	.byte	0xe
	.byte	0x6
	.byte	0xc
	.short	0x155
	.align	2, 0
	.type	 sWindowTemplate_YesNoBox,object
	.size	 sWindowTemplate_YesNoBox,8
sWindowTemplate_YesNoBox:
	.byte	0x0
	.byte	0x17
	.byte	0xf
	.byte	0x6
	.byte	0x4
	.byte	0xc
	.short	0x155
	.align	2, 0
	.type	 sWindowTemplate_7by8,object
	.size	 sWindowTemplate_7by8,8
sWindowTemplate_7by8:
	.byte	0x0
	.byte	0x16
	.byte	0xb
	.byte	0x7
	.byte	0x8
	.byte	0xc
	.short	0x155
	.align	2, 0
	.type	 sWindowTemplate_7by6,object
	.size	 sWindowTemplate_7by6,8
sWindowTemplate_7by6:
	.byte	0x0
	.byte	0x16
	.byte	0xd
	.byte	0x7
	.byte	0x6
	.byte	0xc
	.short	0x155
	.align	2, 0
	.type	 sWindowTemplate_7by4,object
	.size	 sWindowTemplate_7by4,8
sWindowTemplate_7by4:
	.byte	0x0
	.byte	0x16
	.byte	0xf
	.byte	0x7
	.byte	0x4
	.byte	0xc
	.short	0x155
	.align	2, 0
	.type	 sListMenuItems_CardsOrNews,object
sListMenuItems_CardsOrNews:
	.word	gText_WonderCards
	.word	0x0
	.word	gText_WonderNews
	.word	0x1
	.word	gText_Exit3
	.word	-0x2
	.size	 sListMenuItems_CardsOrNews,24
	.align	2, 0
	.type	 sListMenuItems_WirelessOrFriend,object
sListMenuItems_WirelessOrFriend:
	.word	gText_WirelessCommunication
	.word	0x0
	.word	gText_Friend2
	.word	0x1
	.word	gText_Cancel2
	.word	-0x2
	.size	 sListMenuItems_WirelessOrFriend,24
	.align	2, 0
	.type	 sListMenuTemplate_ThreeOptions,object
	.size	 sListMenuTemplate_ThreeOptions,24
sListMenuTemplate_ThreeOptions:
	.word	0x0
	.word	ListMenuDefaultCursorMoveFunc
	.word	0x0
	.short	0x3
	.short	0x3
	.byte	0x0
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x21
	.byte	0x31
	.byte	0x0
	.byte	0x1
	.align	2, 0
	.type	 sListMenuItems_ReceiveSendToss,object
sListMenuItems_ReceiveSendToss:
	.word	gText_Receive
	.word	0x0
	.word	gText_Send
	.word	0x1
	.word	gText_Toss
	.word	0x2
	.word	gText_Cancel2
	.word	-0x2
	.size	 sListMenuItems_ReceiveSendToss,32
	.align	2, 0
	.type	 sListMenuItems_ReceiveToss,object
sListMenuItems_ReceiveToss:
	.word	gText_Receive
	.word	0x0
	.word	gText_Toss
	.word	0x2
	.word	gText_Cancel2
	.word	-0x2
	.size	 sListMenuItems_ReceiveToss,24
	.align	2, 0
	.type	 sListMenuItems_ReceiveSend,object
sListMenuItems_ReceiveSend:
	.word	gText_Receive
	.word	0x0
	.word	gText_Send
	.word	0x1
	.word	gText_Cancel2
	.word	-0x2
	.size	 sListMenuItems_ReceiveSend,24
	.align	2, 0
	.type	 sListMenuItems_Receive,object
sListMenuItems_Receive:
	.word	gText_Receive
	.word	0x0
	.word	gText_Cancel2
	.word	-0x2
	.size	 sListMenuItems_Receive,16
	.align	2, 0
	.type	 sListMenu_ReceiveSendToss,object
	.size	 sListMenu_ReceiveSendToss,24
sListMenu_ReceiveSendToss:
	.word	sListMenuItems_ReceiveSendToss
	.word	ListMenuDefaultCursorMoveFunc
	.word	0x0
	.short	0x4
	.short	0x4
	.byte	0x0
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x21
	.byte	0x31
	.byte	0x0
	.byte	0x1
	.align	2, 0
	.type	 sListMenu_ReceiveToss,object
	.size	 sListMenu_ReceiveToss,24
sListMenu_ReceiveToss:
	.word	sListMenuItems_ReceiveToss
	.word	ListMenuDefaultCursorMoveFunc
	.word	0x0
	.short	0x3
	.short	0x3
	.byte	0x0
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x21
	.byte	0x31
	.byte	0x0
	.byte	0x1
	.align	2, 0
	.type	 sListMenu_ReceiveSend,object
	.size	 sListMenu_ReceiveSend,24
sListMenu_ReceiveSend:
	.word	sListMenuItems_ReceiveSend
	.word	ListMenuDefaultCursorMoveFunc
	.word	0x0
	.short	0x3
	.short	0x3
	.byte	0x0
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x21
	.byte	0x31
	.byte	0x0
	.byte	0x1
	.align	2, 0
	.type	 sListMenu_Receive,object
	.size	 sListMenu_Receive,24
sListMenu_Receive:
	.word	sListMenuItems_Receive
	.word	ListMenuDefaultCursorMoveFunc
	.word	0x0
	.short	0x2
	.short	0x2
	.byte	0x0
	.byte	0x0
	.byte	0x8
	.byte	0x0
	.byte	0x21
	.byte	0x31
	.byte	0x0
	.byte	0x1
	.align	2, 0
	.type	 Unref_082F0710,object
Unref_082F0710:
	.word	gText_VarietyOfEventsImportedWireless
	.word	gText_WonderCardsInPossession
	.word	gText_ReadNewsThatArrived
	.word	gText_ReturnToTitle
	.size	 Unref_082F0710,16
	.globl	sMG_Ereader_TextColor_1
	.align	1, 0
	.type	 sMG_Ereader_TextColor_1,object
sMG_Ereader_TextColor_1:
	.byte	0x0
	.byte	0x1
	.byte	0x2
	.size	 sMG_Ereader_TextColor_1,3
	.globl	sMG_Ereader_TextColor_1_Copy
	.align	1, 0
	.type	 sMG_Ereader_TextColor_1_Copy,object
sMG_Ereader_TextColor_1_Copy:
	.byte	0x0
	.byte	0x1
	.byte	0x2
	.size	 sMG_Ereader_TextColor_1_Copy,3
	.globl	sMG_Ereader_TextColor_2
	.align	1, 0
	.type	 sMG_Ereader_TextColor_2,object
sMG_Ereader_TextColor_2:
	.byte	0x1
	.byte	0x2
	.byte	0x3
	.size	 sMG_Ereader_TextColor_2,3
.text
	.align	2, 0
	.globl	vblankcb_mystery_gift_e_reader_run
	.type	 vblankcb_mystery_gift_e_reader_run,function
	.thumb_func
vblankcb_mystery_gift_e_reader_run:
	push	{lr}
	bl	ProcessSpriteCopyRequests
	bl	LoadOam
	bl	TransferPlttBuffer
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 vblankcb_mystery_gift_e_reader_run,.Lfe1-vblankcb_mystery_gift_e_reader_run
	.align	2, 0
	.globl	c2_mystery_gift_e_reader_run
	.type	 c2_mystery_gift_e_reader_run,function
	.thumb_func
c2_mystery_gift_e_reader_run:
	push	{lr}
	bl	RunTasks
	bl	RunTextPrinters
	bl	AnimateSprites
	bl	BuildOamBuffer
	pop	{r0}
	bx	r0
.Lfe2:
	.size	 c2_mystery_gift_e_reader_run,.Lfe2-c2_mystery_gift_e_reader_run
	.align	2, 0
	.globl	HandleMysteryGiftOrEReaderSetup
	.type	 HandleMysteryGiftOrEReaderSetup,function
	.thumb_func
HandleMysteryGiftOrEReaderSetup:
	push	{r4, r5, r6, r7, lr}
	add	sp, sp, #-0xc
	add	r7, r0, #0
	ldr	r0, .L15
	mov	r1, #0x87
	lsl	r1, r1, #0x3
	add	r6, r0, r1
	ldrb	r0, [r6]
	cmp	r0, #0x1
	bne	.LCB40
	b	.L7	@long jump
.LCB40:
	cmp	r0, #0x1
	bgt	.L12	@cond_branch
	cmp	r0, #0
	beq	.L6	@cond_branch
	b	.L5
.L16:
	.align	2, 0
.L15:
	.word	gMain
.L12:
	cmp	r0, #0x2
	bne	.LCB55
	b	.L8	@long jump
.LCB55:
	cmp	r0, #0x3
	bne	.LCB57
	b	.L9	@long jump
.LCB57:
	b	.L5
.L6:
	mov	r0, #0x0
	bl	SetVBlankCallback
	bl	ResetPaletteFade
	bl	ResetSpriteData
	bl	FreeAllSpritePalettes
	bl	ResetTasks
	bl	ScanlineEffect_Stop
	mov	r0, #0x0
	bl	ResetBgsAndClearDma3BusyFlags
	ldr	r1, .L17
	mov	r0, #0x0
	mov	r2, #0x4
	bl	InitBgsFromTemplates
	mov	r0, #0x0
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ChangeBgX
	mov	r0, #0x0
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ChangeBgY
	mov	r0, #0x1
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ChangeBgX
	mov	r0, #0x1
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ChangeBgY
	mov	r0, #0x2
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ChangeBgX
	mov	r0, #0x2
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ChangeBgY
	mov	r0, #0x3
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ChangeBgX
	mov	r0, #0x3
	mov	r1, #0x0
	mov	r2, #0x0
	bl	ChangeBgY
	mov	r4, #0x80
	lsl	r4, r4, #0x4
	add	r0, r4, #0
	bl	Alloc
	add	r1, r0, #0
	mov	r0, #0x3
	bl	SetBgTilemapBuffer
	add	r0, r4, #0
	bl	Alloc
	add	r1, r0, #0
	mov	r0, #0x2
	bl	SetBgTilemapBuffer
	add	r0, r4, #0
	bl	Alloc
	add	r1, r0, #0
	mov	r0, #0x1
	bl	SetBgTilemapBuffer
	add	r0, r4, #0
	bl	Alloc
	add	r1, r0, #0
	mov	r0, #0x0
	bl	SetBgTilemapBuffer
	mov	r0, #0x3
	bl	bgid_upload_textbox_1
	ldr	r0, .L17+0x4
	bl	InitWindows
	bl	DeactivateAllTextPrinters
	mov	r1, #0xc0
	lsl	r1, r1, #0x7
	mov	r0, #0x0
	bl	ClearGpuRegBits
	mov	r0, #0x50
	mov	r1, #0x0
	bl	SetGpuReg
	mov	r0, #0x52
	mov	r1, #0x0
	bl	SetGpuReg
	mov	r0, #0x54
	mov	r1, #0x0
	bl	SetGpuReg
	b	.L14
.L18:
	.align	2, 0
.L17:
	.word	sBGTemplates
	.word	sMainWindows
.L7:
	ldr	r0, .L19
	mov	r1, #0x0
	mov	r2, #0x20
	bl	LoadPalette
	mov	r0, #0x2
	bl	GetTextWindowPalette
	mov	r1, #0xd0
	mov	r2, #0x20
	bl	LoadPalette
	mov	r0, #0xc0
	bl	Menu_LoadStdPalAt
	mov	r0, #0x0
	mov	r1, #0xa
	mov	r2, #0xe0
	bl	LoadUserWindowBorderGfx
	mov	r0, #0x0
	mov	r1, #0x1
	mov	r2, #0xf0
	bl	LoadUserWindowBorderGfx_
	mov	r4, #0x20
	str	r4, [sp]
	str	r4, [sp, #0x4]
	mov	r5, #0x11
	str	r5, [sp, #0x8]
	mov	r0, #0x0
	mov	r1, #0x0
	mov	r2, #0x0
	mov	r3, #0x0
	bl	FillBgTilemapBufferRect
	str	r4, [sp]
	str	r4, [sp, #0x4]
	str	r5, [sp, #0x8]
	mov	r0, #0x1
	mov	r1, #0x0
	mov	r2, #0x0
	mov	r3, #0x0
	bl	FillBgTilemapBufferRect
	str	r4, [sp]
	str	r4, [sp, #0x4]
	str	r5, [sp, #0x8]
	mov	r0, #0x2
	mov	r1, #0x0
	mov	r2, #0x0
	mov	r3, #0x0
	bl	FillBgTilemapBufferRect
	mov	r0, #0x3
	bl	MG_DrawCheckerboardPattern
	lsl	r0, r7, #0x18
	lsr	r0, r0, #0x18
	mov	r1, #0x0
	bl	PrintMysteryGiftOrEReaderTopMenu
	b	.L14
.L20:
	.align	2, 0
.L19:
	.word	gUnkTextboxBorderPal
.L8:
	mov	r0, #0x3
	bl	CopyBgTilemapBufferToVram
	mov	r0, #0x2
	bl	CopyBgTilemapBufferToVram
	mov	r0, #0x1
	bl	CopyBgTilemapBufferToVram
	mov	r0, #0x0
	bl	CopyBgTilemapBufferToVram
.L14:
	ldrb	r0, [r6]
	add	r0, r0, #0x1
	strb	r0, [r6]
	b	.L5
.L9:
	mov	r0, #0x0
	bl	ShowBg
	mov	r0, #0x3
	bl	ShowBg
	mov	r0, #0xf6
	lsl	r0, r0, #0x1
	bl	PlayBGM
	ldr	r0, .L21
	bl	SetVBlankCallback
	mov	r0, #0xc5
	bl	EnableInterrupts
	mov	r0, #0x1
	b	.L13
.L22:
	.align	2, 0
.L21:
	.word	vblankcb_mystery_gift_e_reader_run
.L5:
	mov	r0, #0x0
.L13:
	add	sp, sp, #0xc
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe3:
	.size	 HandleMysteryGiftOrEReaderSetup,.Lfe3-HandleMysteryGiftOrEReaderSetup
	.align	2, 0
	.globl	c2_mystery_gift
	.type	 c2_mystery_gift,function
	.thumb_func
c2_mystery_gift:
	push	{lr}
	mov	r0, #0x0
	bl	HandleMysteryGiftOrEReaderSetup
	cmp	r0, #0
	beq	.L24	@cond_branch
	ldr	r0, .L25
	bl	SetMainCallback2
	ldr	r1, .L25+0x4
	mov	r0, #0x0
	strb	r0, [r1]
	bl	task_add_00_mystery_gift
.L24:
	bl	RunTasks
	pop	{r0}
	bx	r0
.L26:
	.align	2, 0
.L25:
	.word	c2_mystery_gift_e_reader_run
	.word	gGiftIsFromEReader
.Lfe4:
	.size	 c2_mystery_gift,.Lfe4-c2_mystery_gift
	.align	2, 0
	.globl	c2_ereader
	.type	 c2_ereader,function
	.thumb_func
c2_ereader:
	push	{lr}
	mov	r0, #0x1
	bl	HandleMysteryGiftOrEReaderSetup
	cmp	r0, #0
	beq	.L28	@cond_branch
	ldr	r0, .L29
	bl	SetMainCallback2
	ldr	r1, .L29+0x4
	mov	r0, #0x1
	strb	r0, [r1]
	bl	task_add_00_ereader
.L28:
	pop	{r0}
	bx	r0
.L30:
	.align	2, 0
.L29:
	.word	c2_mystery_gift_e_reader_run
	.word	gGiftIsFromEReader
.Lfe5:
	.size	 c2_ereader,.Lfe5-c2_ereader
	.align	2, 0
	.globl	MainCB_FreeAllBuffersAndReturnToInitTitleScreen
	.type	 MainCB_FreeAllBuffersAndReturnToInitTitleScreen,function
	.thumb_func
MainCB_FreeAllBuffersAndReturnToInitTitleScreen:
	push	{lr}
	ldr	r1, .L32
	mov	r0, #0x0
	strb	r0, [r1]
	bl	FreeAllWindowBuffers
	mov	r0, #0x0
	bl	GetBgTilemapBuffer
	bl	Free
	mov	r0, #0x1
	bl	GetBgTilemapBuffer
	bl	Free
	mov	r0, #0x2
	bl	GetBgTilemapBuffer
	bl	Free
	mov	r0, #0x3
	bl	GetBgTilemapBuffer
	bl	Free
	ldr	r0, .L32+0x4
	bl	SetMainCallback2
	pop	{r0}
	bx	r0
.L33:
	.align	2, 0
.L32:
	.word	gGiftIsFromEReader
	.word	CB2_InitTitleScreen
.Lfe6:
	.size	 MainCB_FreeAllBuffersAndReturnToInitTitleScreen,.Lfe6-MainCB_FreeAllBuffersAndReturnToInitTitleScreen
	.align	2, 0
	.globl	PrintMysteryGiftOrEReaderTopMenu
	.type	 PrintMysteryGiftOrEReaderTopMenu,function
	.thumb_func
PrintMysteryGiftOrEReaderTopMenu:
	push	{r4, r5, r6, r7, lr}
	add	sp, sp, #-0x14
	add	r4, r0, #0
	add	r5, r1, #0
	lsl	r4, r4, #0x18
	lsr	r4, r4, #0x18
	mov	r0, #0x0
	mov	r1, #0x0
	bl	FillWindowPixelBuffer
	cmp	r4, #0
	bne	.L35	@cond_branch
	ldr	r0, .L39
	ldr	r7, .L39+0x4
	cmp	r5, #0
	bne	.L38	@cond_branch
	ldr	r7, .L39+0x8
	b	.L38
.L40:
	.align	2, 0
.L39:
	.word	gText_MysteryGift
	.word	gText_PickOKCancel
	.word	gText_PickOKExit
.L35:
	ldr	r0, .L41
	ldr	r7, .L41+0x4
.L38:
	mov	r4, #0x0
	str	r4, [sp]
	str	r4, [sp, #0x4]
	ldr	r6, .L41+0x8
	str	r6, [sp, #0x8]
	mov	r5, #0x1
	neg	r5, r5
	str	r5, [sp, #0xc]
	str	r0, [sp, #0x10]
	mov	r0, #0x0
	mov	r1, #0x1
	mov	r2, #0x4
	mov	r3, #0x1
	bl	AddTextPrinterParameterized4
	mov	r0, #0x0
	add	r1, r7, #0
	mov	r2, #0xde
	bl	GetStringRightAlignXOffset
	add	r2, r0, #0
	lsl	r2, r2, #0x18
	lsr	r2, r2, #0x18
	str	r4, [sp]
	str	r4, [sp, #0x4]
	str	r6, [sp, #0x8]
	str	r5, [sp, #0xc]
	str	r7, [sp, #0x10]
	mov	r0, #0x0
	mov	r1, #0x0
	mov	r3, #0x1
	bl	AddTextPrinterParameterized4
	mov	r0, #0x0
	mov	r1, #0x2
	bl	CopyWindowToVram
	mov	r0, #0x0
	bl	PutWindowTilemap
	add	sp, sp, #0x14
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.L42:
	.align	2, 0
.L41:
	.word	gJPText_MysteryGift
	.word	gJPText_DecideStop
	.word	sMG_Ereader_TextColor_1
.Lfe7:
	.size	 PrintMysteryGiftOrEReaderTopMenu,.Lfe7-PrintMysteryGiftOrEReaderTopMenu
	.align	2, 0
	.globl	MG_DrawTextBorder
	.type	 MG_DrawTextBorder,function
	.thumb_func
MG_DrawTextBorder:
	push	{lr}
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	mov	r1, #0x1
	mov	r2, #0xf
	bl	DrawTextBorderOuter
	pop	{r0}
	bx	r0
.Lfe8:
	.size	 MG_DrawTextBorder,.Lfe8-MG_DrawTextBorder
	.align	2, 0
	.globl	MG_DrawCheckerboardPattern
	.type	 MG_DrawCheckerboardPattern,function
	.thumb_func
MG_DrawCheckerboardPattern:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	add	sp, sp, #-0xc
	add	r4, r0, #0
	mov	r0, #0x0
	mov	r9, r0
	lsl	r4, r4, #0x18
	lsr	r0, r4, #0x18
	mov	r1, #0x20
	str	r1, [sp]
	mov	r1, #0x2
	str	r1, [sp, #0x4]
	mov	r1, #0x11
	str	r1, [sp, #0x8]
	mov	r1, #0x3
	mov	r2, #0x0
	mov	r3, #0x0
	bl	FillBgTilemapBufferRect
	mov	r8, r4
	mov	r4, #0x1
.L48:
	mov	r7, #0x0
	mov	r0, r9
	add	r0, r0, #0x2
	mov	r1, #0x1
	add	r1, r1, r9
	mov	sl, r1
	lsl	r5, r0, #0x18
	mov	r6, #0x0
.L52:
	mov	r1, r9
	and	r1, r1, r4
	add	r0, r7, #0
	and	r0, r0, r4
	cmp	r1, r0
	beq	.L53	@cond_branch
	lsr	r2, r6, #0x18
	str	r4, [sp]
	str	r4, [sp, #0x4]
	mov	r0, #0x11
	str	r0, [sp, #0x8]
	mov	r1, r8
	lsr	r0, r1, #0x18
	mov	r1, #0x1
	lsr	r3, r5, #0x18
	bl	FillBgTilemapBufferRect
	b	.L51
.L53:
	lsr	r2, r6, #0x18
	str	r4, [sp]
	str	r4, [sp, #0x4]
	mov	r0, #0x11
	str	r0, [sp, #0x8]
	mov	r1, r8
	lsr	r0, r1, #0x18
	mov	r1, #0x2
	lsr	r3, r5, #0x18
	bl	FillBgTilemapBufferRect
.L51:
	mov	r0, #0x80
	lsl	r0, r0, #0x11
	add	r6, r6, r0
	add	r7, r7, #0x1
	cmp	r7, #0x1f
	ble	.L52	@cond_branch
	mov	r9, sl
	mov	r1, r9
	cmp	r1, #0x11
	ble	.L48	@cond_branch
	add	sp, sp, #0xc
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe9:
	.size	 MG_DrawCheckerboardPattern,.Lfe9-MG_DrawCheckerboardPattern
	.align	2, 0
	.globl	ClearScreenInBg0
	.type	 ClearScreenInBg0,function
	.thumb_func
ClearScreenInBg0:
	push	{lr}
	add	sp, sp, #-0xc
	cmp	r0, #0
	beq	.L59	@cond_branch
	cmp	r0, #0x1
	beq	.L60	@cond_branch
	b	.L58
.L59:
	mov	r0, #0x20
	str	r0, [sp]
	str	r0, [sp, #0x4]
	mov	r0, #0x11
	str	r0, [sp, #0x8]
	mov	r0, #0x0
	mov	r1, #0x0
	mov	r2, #0x0
	mov	r3, #0x0
	bl	FillBgTilemapBufferRect
	b	.L58
.L60:
	mov	r0, #0x20
	str	r0, [sp]
	mov	r0, #0x1e
	str	r0, [sp, #0x4]
	mov	r0, #0x11
	str	r0, [sp, #0x8]
	mov	r0, #0x0
	mov	r1, #0x0
	mov	r2, #0x0
	mov	r3, #0x2
	bl	FillBgTilemapBufferRect
.L58:
	mov	r0, #0x0
	bl	CopyBgTilemapBufferToVram
	add	sp, sp, #0xc
	pop	{r0}
	bx	r0
.Lfe10:
	.size	 ClearScreenInBg0,.Lfe10-ClearScreenInBg0
	.align	2, 0
	.globl	AddTextPrinterToWindow1
	.type	 AddTextPrinterToWindow1,function
	.thumb_func
AddTextPrinterToWindow1:
	push	{r4, lr}
	add	sp, sp, #-0x14
	add	r1, r0, #0
	ldr	r4, .L64
	add	r0, r4, #0
	bl	StringExpandPlaceholders
	mov	r0, #0x1
	mov	r1, #0x11
	bl	FillWindowPixelBuffer
	mov	r1, #0x0
	str	r1, [sp]
	str	r1, [sp, #0x4]
	ldr	r0, .L64+0x4
	str	r0, [sp, #0x8]
	str	r1, [sp, #0xc]
	str	r4, [sp, #0x10]
	mov	r0, #0x1
	mov	r1, #0x1
	mov	r2, #0x0
	mov	r3, #0x1
	bl	AddTextPrinterParameterized4
	mov	r0, #0x1
	mov	r1, #0x1
	mov	r2, #0xf
	bl	DrawTextBorderOuter
	mov	r0, #0x1
	bl	PutWindowTilemap
	mov	r0, #0x1
	mov	r1, #0x3
	bl	CopyWindowToVram
	add	sp, sp, #0x14
	pop	{r4}
	pop	{r0}
	bx	r0
.L65:
	.align	2, 0
.L64:
	.word	gStringVar4
	.word	sMG_Ereader_TextColor_2
.Lfe11:
	.size	 AddTextPrinterToWindow1,.Lfe11-AddTextPrinterToWindow1
	.align	2, 0
	.type	 ClearTextWindow,function
	.thumb_func
ClearTextWindow:
	push	{lr}
	mov	r0, #0x1
	bl	rbox_fill_rectangle
	mov	r0, #0x1
	bl	ClearWindowTilemap
	mov	r0, #0x1
	mov	r1, #0x1
	bl	CopyWindowToVram
	pop	{r0}
	bx	r0
.Lfe12:
	.size	 ClearTextWindow,.Lfe12-ClearTextWindow
	.align	2, 0
	.globl	MG_PrintTextOnWindow1AndWaitButton
	.type	 MG_PrintTextOnWindow1AndWaitButton,function
	.thumb_func
MG_PrintTextOnWindow1AndWaitButton:
	push	{r4, lr}
	add	sp, sp, #-0xc
	add	r4, r0, #0
	add	r0, r1, #0
	ldrb	r2, [r4]
	cmp	r2, #0x1
	beq	.L71	@cond_branch
	cmp	r2, #0x1
	bgt	.L77	@cond_branch
	cmp	r2, #0
	beq	.L69	@cond_branch
	b	.L68
.L77:
	cmp	r2, #0x2
	beq	.L73	@cond_branch
	cmp	r2, #0xff
	beq	.L74	@cond_branch
	b	.L68
.L69:
	bl	AddTextPrinterToWindow1
	b	.L70
.L71:
	mov	r0, #0x0
	str	r0, [sp]
	ldr	r0, .L80
	str	r0, [sp, #0x4]
	add	r0, r0, #0x1
	str	r0, [sp, #0x8]
	mov	r0, #0x1
	mov	r1, #0xd0
	mov	r2, #0x14
	mov	r3, #0x1
	bl	DrawDownArrow
	ldr	r0, .L80+0x4
	ldrh	r1, [r0, #0x2e]
	mov	r0, #0x3
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L68	@cond_branch
.L70:
	ldrb	r0, [r4]
	add	r0, r0, #0x1
	b	.L79
.L81:
	.align	2, 0
.L80:
	.word	sDownArrowCounterAndYCoordIdx
	.word	gMain
.L73:
	mov	r0, #0x1
	str	r0, [sp]
	ldr	r0, .L82
	str	r0, [sp, #0x4]
	add	r0, r0, #0x1
	str	r0, [sp, #0x8]
	mov	r0, #0x1
	mov	r1, #0xd0
	mov	r2, #0x14
	mov	r3, #0x1
	bl	DrawDownArrow
	mov	r0, #0x0
	strb	r0, [r4]
	bl	ClearTextWindow
	mov	r0, #0x1
	b	.L78
.L83:
	.align	2, 0
.L82:
	.word	sDownArrowCounterAndYCoordIdx
.L74:
	mov	r0, #0x2
.L79:
	strb	r0, [r4]
.L68:
	mov	r0, #0x0
.L78:
	add	sp, sp, #0xc
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe13:
	.size	 MG_PrintTextOnWindow1AndWaitButton,.Lfe13-MG_PrintTextOnWindow1AndWaitButton
	.align	2, 0
	.type	 HideDownArrow,function
	.thumb_func
HideDownArrow:
	push	{lr}
	add	sp, sp, #-0xc
	mov	r0, #0x0
	str	r0, [sp]
	ldr	r0, .L85
	str	r0, [sp, #0x4]
	add	r0, r0, #0x1
	str	r0, [sp, #0x8]
	mov	r0, #0x1
	mov	r1, #0xd0
	mov	r2, #0x14
	mov	r3, #0x1
	bl	DrawDownArrow
	add	sp, sp, #0xc
	pop	{r0}
	bx	r0
.L86:
	.align	2, 0
.L85:
	.word	sDownArrowCounterAndYCoordIdx
.Lfe14:
	.size	 HideDownArrow,.Lfe14-HideDownArrow
	.align	2, 0
	.type	 ShowDownArrow,function
	.thumb_func
ShowDownArrow:
	push	{lr}
	add	sp, sp, #-0xc
	mov	r0, #0x1
	str	r0, [sp]
	ldr	r0, .L88
	str	r0, [sp, #0x4]
	add	r0, r0, #0x1
	str	r0, [sp, #0x8]
	mov	r0, #0x1
	mov	r1, #0xd0
	mov	r2, #0x14
	mov	r3, #0x1
	bl	DrawDownArrow
	add	sp, sp, #0xc
	pop	{r0}
	bx	r0
.L89:
	.align	2, 0
.L88:
	.word	sDownArrowCounterAndYCoordIdx
.Lfe15:
	.size	 ShowDownArrow,.Lfe15-ShowDownArrow
	.align	2, 0
	.globl	unref_HideDownArrowAndWaitButton
	.type	 unref_HideDownArrowAndWaitButton,function
	.thumb_func
unref_HideDownArrowAndWaitButton:
	push	{r4, lr}
	add	r4, r0, #0
	ldrb	r0, [r4]
	cmp	r0, #0
	beq	.L92	@cond_branch
	cmp	r0, #0x1
	beq	.L94	@cond_branch
	b	.L91
.L92:
	bl	HideDownArrow
	ldr	r0, .L98
	ldrh	r1, [r0, #0x2e]
	mov	r0, #0x3
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L91	@cond_branch
	ldrb	r0, [r4]
	add	r0, r0, #0x1
	strb	r0, [r4]
	b	.L91
.L99:
	.align	2, 0
.L98:
	.word	gMain
.L94:
	bl	ShowDownArrow
	mov	r0, #0x0
	strb	r0, [r4]
	mov	r0, #0x1
	b	.L97
.L91:
	mov	r0, #0x0
.L97:
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe16:
	.size	 unref_HideDownArrowAndWaitButton,.Lfe16-unref_HideDownArrowAndWaitButton
	.align	2, 0
	.type	 PrintStringAndWait2Seconds,function
	.thumb_func
PrintStringAndWait2Seconds:
	push	{r4, lr}
	add	r4, r0, #0
	ldrb	r0, [r4]
	cmp	r0, #0
	bne	.L101	@cond_branch
	add	r0, r1, #0
	bl	AddTextPrinterToWindow1
.L101:
	ldrb	r0, [r4]
	add	r0, r0, #0x1
	strb	r0, [r4]
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	cmp	r0, #0x78
	bhi	.L102	@cond_branch
	mov	r0, #0x0
	b	.L104
.L102:
	mov	r0, #0x0
	strb	r0, [r4]
	bl	ClearTextWindow
	mov	r0, #0x1
.L104:
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe17:
	.size	 PrintStringAndWait2Seconds,.Lfe17-PrintStringAndWait2Seconds
	.align	2, 0
	.type	 MysteryGift_HandleThreeOptionMenu,function
	.thumb_func
MysteryGift_HandleThreeOptionMenu:
	push	{r4, r5, lr}
	add	sp, sp, #-0x24
	lsl	r2, r2, #0x18
	add	r1, sp, #0x4
	ldr	r0, .L113
	ldmia	r0!, {r3, r4, r5}
	stmia	r1!, {r3, r4, r5}
	ldmia	r0!, {r3, r4, r5}
	stmia	r1!, {r3, r4, r5}
	ldr	r0, .L113+0x4
	ldr	r1, [r0, #0x4]		@ created by thumb_load_double_from_address
	ldr	r0, [r0]		@ created by thumb_load_double_from_address
	str	r0, [sp, #0x1c]
	str	r1, [sp, #0x20]
	cmp	r2, #0
	bne	.L106	@cond_branch
	ldr	r0, .L113+0x8
	b	.L112
.L114:
	.align	2, 0
.L113:
	.word	sListMenuTemplate_ThreeOptions
	.word	sWindowTemplate_ThreeOptions
	.word	sListMenuItems_CardsOrNews
.L106:
	ldr	r0, .L115
.L112:
	str	r0, [sp, #0x4]
	add	r0, sp, #0x4
	bl	Intl_GetListMenuWidth
	add	r3, r0, #0
	mov	r0, #0x1
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L108	@cond_branch
	add	r3, r3, #0x1
.L108:
	lsl	r1, r3, #0x18
	ldr	r0, .L115+0x4
	ldr	r2, [sp, #0x1c]
	and	r2, r2, r0
	orr	r2, r2, r1
	str	r2, [sp, #0x1c]
	cmp	r3, #0x1d
	bgt	.L109	@cond_branch
	mov	r0, #0x1e
	sub	r0, r0, r3
	lsr	r1, r0, #0x1f
	add	r0, r0, r1
	asr	r0, r0, #0x1
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x10
	ldr	r1, .L115+0x8
	and	r1, r1, r2
	orr	r1, r1, r0
	str	r1, [sp, #0x1c]
	b	.L110
.L116:
	.align	2, 0
.L115:
	.word	sListMenuItems_WirelessOrFriend
	.word	0xffffff
	.word	-0xff01
.L109:
	ldr	r0, .L117
	and	r2, r2, r0
	str	r2, [sp, #0x1c]
.L110:
	add	r0, sp, #0x1c
	mov	r1, #0xe0
	str	r1, [sp]
	add	r1, sp, #0x4
	mov	r2, #0x1
	mov	r3, #0xa
	bl	DoMysteryGiftListMenu
	add	r4, r0, #0
	mov	r0, #0x1
	neg	r0, r0
	cmp	r4, r0
	beq	.L111	@cond_branch
	mov	r0, #0x2
	bl	ClearWindowTilemap
	mov	r0, #0x2
	mov	r1, #0x1
	bl	CopyWindowToVram
.L111:
	add	r0, r4, #0
	add	sp, sp, #0x24
	pop	{r4, r5}
	pop	{r1}
	bx	r1
.L118:
	.align	2, 0
.L117:
	.word	-0xff01
.Lfe18:
	.size	 MysteryGift_HandleThreeOptionMenu,.Lfe18-MysteryGift_HandleThreeOptionMenu
	.align	2, 0
	.globl	mevent_message_print_and_prompt_yes_no
	.type	 mevent_message_print_and_prompt_yes_no,function
	.thumb_func
mevent_message_print_and_prompt_yes_no:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-0x1c
	add	r5, r0, #0
	add	r4, r1, #0
	add	r1, r3, #0
	lsl	r2, r2, #0x18
	lsr	r6, r2, #0x18
	ldrb	r0, [r5]
	cmp	r0, #0x1
	beq	.L124	@cond_branch
	cmp	r0, #0x1
	bgt	.L132	@cond_branch
	cmp	r0, #0
	beq	.L121	@cond_branch
	b	.L120
.L132:
	cmp	r0, #0x2
	beq	.L127	@cond_branch
	cmp	r0, #0xff
	beq	.L129	@cond_branch
	b	.L120
.L121:
	ldr	r0, .L137
	bl	StringExpandPlaceholders
	cmp	r6, #0
	bne	.L122	@cond_branch
	ldr	r0, .L137+0x4
	b	.L134
.L138:
	.align	2, 0
.L137:
	.word	gStringVar4
	.word	sWindowTemplate_PromptYesOrNo_Width28
.L122:
	ldr	r0, .L139
.L134:
	bl	AddWindow
	strh	r0, [r4]
	ldrb	r0, [r4]
	mov	r1, #0x11
	bl	FillWindowPixelBuffer
	ldrb	r0, [r4]
	mov	r2, #0x0
	str	r2, [sp]
	str	r2, [sp, #0x4]
	ldr	r1, .L139+0x4
	str	r1, [sp, #0x8]
	str	r2, [sp, #0xc]
	ldr	r1, .L139+0x8
	str	r1, [sp, #0x10]
	mov	r1, #0x1
	mov	r3, #0x1
	bl	AddTextPrinterParameterized4
	ldrb	r0, [r4]
	mov	r1, #0x1
	mov	r2, #0xf
	bl	DrawTextBorderOuter
	ldrb	r0, [r4]
	mov	r1, #0x2
	bl	CopyWindowToVram
	ldrb	r0, [r4]
	bl	PutWindowTilemap
	b	.L135
.L140:
	.align	2, 0
.L139:
	.word	sWindowTemplate_PromptYesOrNo_Width20
	.word	sMG_Ereader_TextColor_2
	.word	gStringVar4
.L124:
	ldr	r0, .L141
	ldr	r1, [r0, #0x4]		@ created by thumb_load_double_from_address
	ldr	r0, [r0]		@ created by thumb_load_double_from_address
	str	r0, [sp, #0x14]
	str	r1, [sp, #0x18]
	cmp	r6, #0
	bne	.L125	@cond_branch
	ldr	r0, .L141+0x4
	ldr	r1, [sp, #0x14]
	and	r1, r1, r0
	mov	r0, #0x90
	lsl	r0, r0, #0xc
	b	.L136
.L142:
	.align	2, 0
.L141:
	.word	sWindowTemplate_YesNoBox
	.word	-0xff0001
.L125:
	ldr	r0, .L143
	ldr	r1, [sp, #0x14]
	and	r1, r1, r0
	mov	r0, #0xf0
	lsl	r0, r0, #0xc
.L136:
	orr	r1, r1, r0
	str	r1, [sp, #0x14]
	add	r0, sp, #0x14
	mov	r1, #0xa
	mov	r2, #0xe
	mov	r3, #0x0
	bl	CreateYesNoMenu
.L135:
	ldrb	r0, [r5]
	add	r0, r0, #0x1
	strb	r0, [r5]
	b	.L120
.L144:
	.align	2, 0
.L143:
	.word	-0xff0001
.L127:
	bl	Menu_ProcessInputNoWrapClearOnChoose
	lsl	r0, r0, #0x18
	asr	r6, r0, #0x18
	mov	r1, #0x80
	lsl	r1, r1, #0x11
	add	r0, r0, r1
	lsr	r0, r0, #0x18
	cmp	r0, #0x2
	bhi	.L120	@cond_branch
	mov	r0, #0x0
	strb	r0, [r5]
	ldrb	r0, [r4]
	bl	rbox_fill_rectangle
	ldrb	r0, [r4]
	bl	ClearWindowTilemap
	ldrb	r0, [r4]
	mov	r1, #0x1
	bl	CopyWindowToVram
	ldrb	r0, [r4]
	bl	RemoveWindow
	add	r0, r6, #0
	b	.L133
.L129:
	mov	r0, #0x0
	strb	r0, [r5]
	ldrb	r0, [r4]
	bl	rbox_fill_rectangle
	ldrb	r0, [r4]
	bl	ClearWindowTilemap
	ldrb	r0, [r4]
	mov	r1, #0x1
	bl	CopyWindowToVram
	ldrb	r0, [r4]
	bl	RemoveWindow
	mov	r0, #0x1
	neg	r0, r0
	b	.L133
.L120:
	mov	r0, #0x2
	neg	r0, r0
.L133:
	add	sp, sp, #0x1c
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
.Lfe19:
	.size	 mevent_message_print_and_prompt_yes_no,.Lfe19-mevent_message_print_and_prompt_yes_no
	.align	2, 0
	.type	 HandleMysteryGiftListMenu,function
	.thumb_func
HandleMysteryGiftListMenu:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-0x14
	add	r6, r0, #0
	add	r5, r1, #0
	ldrb	r0, [r6]
	cmp	r0, #0x1
	beq	.L150	@cond_branch
	cmp	r0, #0x1
	bgt	.L161	@cond_branch
	cmp	r0, #0
	beq	.L147	@cond_branch
	b	.L146
.L161:
	cmp	r0, #0xff
	bne	.LCB1383
	b	.L158	@long jump
.LCB1383:
	b	.L146
.L147:
	cmp	r2, #0
	bne	.L148	@cond_branch
	ldr	r0, .L164
	ldr	r1, .L164+0x4
	bl	StringExpandPlaceholders
	b	.L149
.L165:
	.align	2, 0
.L164:
	.word	gStringVar4
	.word	gText_WhatToDoWithCards
.L148:
	ldr	r0, .L166
	ldr	r1, .L166+0x4
	bl	StringExpandPlaceholders
.L149:
	ldr	r0, .L166+0x8
	bl	AddWindow
	strh	r0, [r5]
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	mov	r1, #0x11
	bl	FillWindowPixelBuffer
	ldrb	r0, [r5]
	mov	r2, #0x0
	str	r2, [sp]
	str	r2, [sp, #0x4]
	ldr	r1, .L166+0xc
	str	r1, [sp, #0x8]
	str	r2, [sp, #0xc]
	ldr	r1, .L166
	str	r1, [sp, #0x10]
	mov	r1, #0x1
	mov	r3, #0x1
	bl	AddTextPrinterParameterized4
	ldrb	r0, [r5]
	mov	r1, #0x1
	mov	r2, #0xf
	bl	DrawTextBorderOuter
	ldrb	r0, [r5]
	mov	r1, #0x2
	bl	CopyWindowToVram
	ldrb	r0, [r5]
	bl	PutWindowTilemap
	ldrb	r0, [r6]
	add	r0, r0, #0x1
	strb	r0, [r6]
	b	.L146
.L167:
	.align	2, 0
.L166:
	.word	gStringVar4
	.word	gText_WhatToDoWithNews
	.word	sMysteryGiftMenuWindowTemplate
	.word	sMG_Ereader_TextColor_2
.L150:
	cmp	r3, #0
	beq	.L151	@cond_branch
	cmp	r2, #0
	bne	.L152	@cond_branch
	ldr	r0, .L168
	ldr	r1, .L168+0x4
	b	.L163
.L169:
	.align	2, 0
.L168:
	.word	sWindowTemplate_7by6
	.word	sListMenu_ReceiveToss
.L152:
	ldr	r0, .L170
	ldr	r1, .L170+0x4
	b	.L163
.L171:
	.align	2, 0
.L170:
	.word	sWindowTemplate_7by4
	.word	sListMenu_Receive
.L151:
	cmp	r2, #0
	bne	.L155	@cond_branch
	ldr	r0, .L172
	ldr	r1, .L172+0x4
	b	.L163
.L173:
	.align	2, 0
.L172:
	.word	sWindowTemplate_7by8
	.word	sListMenu_ReceiveSendToss
.L155:
	ldr	r0, .L174
	ldr	r1, .L174+0x4
.L163:
	mov	r2, #0xe0
	str	r2, [sp]
	mov	r2, #0x1
	mov	r3, #0xa
	bl	DoMysteryGiftListMenu
	add	r4, r0, #0
	mov	r0, #0x1
	neg	r0, r0
	cmp	r4, r0
	beq	.L146	@cond_branch
	mov	r0, #0x0
	strb	r0, [r6]
	ldrb	r0, [r5]
	bl	rbox_fill_rectangle
	ldrb	r0, [r5]
	bl	ClearWindowTilemap
	ldrb	r0, [r5]
	mov	r1, #0x1
	bl	CopyWindowToVram
	ldrb	r0, [r5]
	bl	RemoveWindow
	add	r0, r4, #0
	b	.L162
.L175:
	.align	2, 0
.L174:
	.word	sWindowTemplate_7by6
	.word	sListMenu_ReceiveSend
.L158:
	mov	r0, #0x0
	strb	r0, [r6]
	ldrb	r0, [r5]
	bl	rbox_fill_rectangle
	ldrb	r0, [r5]
	bl	ClearWindowTilemap
	ldrb	r0, [r5]
	mov	r1, #0x1
	bl	CopyWindowToVram
	ldrb	r0, [r5]
	bl	RemoveWindow
	mov	r0, #0x2
	neg	r0, r0
	b	.L162
.L146:
	mov	r0, #0x1
	neg	r0, r0
.L162:
	add	sp, sp, #0x14
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
.Lfe20:
	.size	 HandleMysteryGiftListMenu,.Lfe20-HandleMysteryGiftListMenu
	.align	2, 0
	.type	 ValidateCardOrNews,function
	.thumb_func
ValidateCardOrNews:
	push	{lr}
	cmp	r0, #0
	beq	.L177	@cond_branch
	bl	ValidateReceivedWonderNews
	b	.L180
.L177:
	bl	ValidateReceivedWonderCard
.L180:
	pop	{r1}
	bx	r1
.Lfe21:
	.size	 ValidateCardOrNews,.Lfe21-ValidateCardOrNews
	.align	2, 0
	.type	 HandleLoadWonderCardOrNews,function
	.thumb_func
HandleLoadWonderCardOrNews:
	push	{r4, r5, lr}
	add	r5, r0, #0
	ldrb	r0, [r5]
	cmp	r0, #0
	beq	.L183	@cond_branch
	cmp	r0, #0x1
	beq	.L186	@cond_branch
	b	.L182
.L183:
	cmp	r1, #0
	bne	.L184	@cond_branch
	bl	GetSavedWonderCard
	add	r4, r0, #0
	bl	sav1_get_mevent_buffer_2
	add	r1, r0, #0
	add	r0, r4, #0
	bl	InitWonderCardResources
	b	.L185
.L184:
	bl	GetSavedWonderNews
	bl	InitWonderNewsResources
.L185:
	ldrb	r0, [r5]
	add	r0, r0, #0x1
	strb	r0, [r5]
	b	.L182
.L186:
	cmp	r1, #0
	bne	.L187	@cond_branch
	bl	FadeToWonderCardMenu
.L188:
	cmp	r0, #0
	bne	.L190	@cond_branch
	b	.L182
.L187:
	bl	FadeToWonderNewsMenu
	b	.L188
.L190:
	mov	r0, #0x0
	strb	r0, [r5]
	mov	r0, #0x1
	b	.L194
.L182:
	mov	r0, #0x0
.L194:
	pop	{r4, r5}
	pop	{r1}
	bx	r1
.Lfe22:
	.size	 HandleLoadWonderCardOrNews,.Lfe22-HandleLoadWonderCardOrNews
	.align	2, 0
	.type	 DestroyNewsOrCard,function
	.thumb_func
DestroyNewsOrCard:
	push	{lr}
	cmp	r0, #0
	bne	.L196	@cond_branch
	bl	DestroyWonderCard
	b	.L197
.L196:
	bl	DestroyWonderNews
.L197:
	mov	r0, #0x1
	pop	{r1}
	bx	r1
.Lfe23:
	.size	 DestroyNewsOrCard,.Lfe23-DestroyNewsOrCard
	.align	2, 0
	.type	 TearDownCardOrNews_ReturnToTopMenu,function
	.thumb_func
TearDownCardOrNews_ReturnToTopMenu:
	push	{lr}
	cmp	r0, #0
	bne	.L199	@cond_branch
	add	r0, r1, #0
	bl	FadeOutFromWonderCard
	cmp	r0, #0
	beq	.L207	@cond_branch
	bl	DestroyWonderCardResources
	b	.L206
.L199:
	add	r0, r1, #0
	bl	FadeOutFromWonderNews
	cmp	r0, #0
	bne	.L203	@cond_branch
.L207:
	mov	r0, #0x0
	b	.L205
.L203:
	bl	DestroyWonderNewsResources
.L206:
	mov	r0, #0x1
.L205:
	pop	{r1}
	bx	r1
.Lfe24:
	.size	 TearDownCardOrNews_ReturnToTopMenu,.Lfe24-TearDownCardOrNews_ReturnToTopMenu
	.align	2, 0
	.type	 mevent_message_prompt_discard,function
	.thumb_func
mevent_message_prompt_discard:
	push	{lr}
	cmp	r2, #0
	beq	.L209	@cond_branch
	ldr	r3, .L214
	b	.L213
.L215:
	.align	2, 0
.L214:
	.word	gText_OkayToDiscardNews
.L209:
	ldr	r3, .L216
.L213:
	mov	r2, #0x1
	bl	mevent_message_print_and_prompt_yes_no
	lsl	r0, r0, #0x18
	asr	r0, r0, #0x18
	pop	{r1}
	bx	r1
.L217:
	.align	2, 0
.L216:
	.word	gText_IfThrowAwayCardEventWontHappen
.Lfe25:
	.size	 mevent_message_prompt_discard,.Lfe25-mevent_message_prompt_discard
	.align	2, 0
	.type	 mevent_message_was_thrown_away,function
	.thumb_func
mevent_message_was_thrown_away:
	push	{lr}
	cmp	r1, #0
	beq	.L219	@cond_branch
	ldr	r1, .L224
	b	.L223
.L225:
	.align	2, 0
.L224:
	.word	gText_WonderNewsThrownAway
.L219:
	ldr	r1, .L226
.L223:
	bl	MG_PrintTextOnWindow1AndWaitButton
	pop	{r1}
	bx	r1
.L227:
	.align	2, 0
.L226:
	.word	gText_WonderCardThrownAway
.Lfe26:
	.size	 mevent_message_was_thrown_away,.Lfe26-mevent_message_was_thrown_away
	.align	2, 0
	.type	 mevent_save_game,function
	.thumb_func
mevent_save_game:
	push	{r4, lr}
	add	r4, r0, #0
	ldrb	r0, [r4]
	cmp	r0, #0x4
	bhi	.L229	@cond_branch
	lsl	r0, r0, #0x2
	ldr	r1, .L240
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L241:
	.align	2, 0
.L240:
	.word	.L236
	.align	2, 0
	.align	2, 0
.L236:
	.word	.L230
	.word	.L231
	.word	.L232
	.word	.L233
	.word	.L235
.L230:
	ldr	r0, .L242
	bl	AddTextPrinterToWindow1
	b	.L239
.L243:
	.align	2, 0
.L242:
	.word	gText_DataWillBeSaved
.L231:
	mov	r0, #0x0
	bl	TrySavingData
	b	.L239
.L232:
	ldr	r0, .L244
	bl	AddTextPrinterToWindow1
	b	.L239
.L245:
	.align	2, 0
.L244:
	.word	gText_SaveCompletedPressA
.L233:
	ldr	r0, .L246
	ldrh	r1, [r0, #0x2e]
	mov	r0, #0x3
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L229	@cond_branch
.L239:
	ldrb	r0, [r4]
	add	r0, r0, #0x1
	strb	r0, [r4]
	b	.L229
.L247:
	.align	2, 0
.L246:
	.word	gMain
.L235:
	mov	r0, #0x0
	strb	r0, [r4]
	bl	ClearTextWindow
	mov	r0, #0x1
	b	.L238
.L229:
	mov	r0, #0x0
.L238:
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe27:
	.size	 mevent_save_game,.Lfe27-mevent_save_game
	.align	2, 0
	.type	 mevent_message,function
	.thumb_func
mevent_message:
	push	{r4, r5, r6, lr}
	add	r4, r0, #0
	lsl	r1, r1, #0x18
	lsr	r6, r1, #0x18
	lsl	r2, r2, #0x18
	lsr	r5, r2, #0x18
	mov	r2, #0x0
	str	r2, [r4]
	cmp	r3, #0xe
	bls	.LCB2010
	b	.L249	@long jump
.LCB2010:
	lsl	r0, r3, #0x2
	ldr	r1, .L274
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L275:
	.align	2, 0
.L274:
	.word	.L271
	.align	2, 0
	.align	2, 0
.L271:
	.word	.L250
	.word	.L251
	.word	.L252
	.word	.L255
	.word	.L258
	.word	.L259
	.word	.L260
	.word	.L261
	.word	.L262
	.word	.L263
	.word	.L264
	.word	.L267
	.word	.L268
	.word	.L269
	.word	.L270
.L250:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L276
	b	.L249
.L277:
	.align	2, 0
.L276:
	.word	gText_NothingSentOver
.L251:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L278
	b	.L249
.L279:
	.align	2, 0
.L278:
	.word	gText_RecordUploadedViaWireless
.L252:
	mov	r0, #0x1
	str	r0, [r4]
	ldr	r2, .L280
	cmp	r5, #0
	bne	.L249	@cond_branch
	ldr	r2, .L280+0x4
	b	.L249
.L281:
	.align	2, 0
.L280:
	.word	gText_WonderCardReceivedFrom
	.word	gText_WonderCardReceived
.L255:
	mov	r0, #0x1
	str	r0, [r4]
	ldr	r2, .L282
	cmp	r5, #0
	bne	.L249	@cond_branch
	ldr	r2, .L282+0x4
	b	.L249
.L283:
	.align	2, 0
.L282:
	.word	gText_WonderNewsReceivedFrom
	.word	gText_WonderNewsReceived
.L258:
	mov	r0, #0x1
	str	r0, [r4]
	ldr	r2, .L284
	b	.L249
.L285:
	.align	2, 0
.L284:
	.word	gText_NewStampReceived
.L259:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L286
	b	.L249
.L287:
	.align	2, 0
.L286:
	.word	gText_AlreadyHadCard
.L260:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L288
	b	.L249
.L289:
	.align	2, 0
.L288:
	.word	gText_AlreadyHadStamp
.L261:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L290
	b	.L249
.L291:
	.align	2, 0
.L290:
	.word	gText_AlreadyHadNews
.L262:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L292
	b	.L249
.L293:
	.align	2, 0
.L292:
	.word	gText_NoMoreRoomForStamps
.L263:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L294
	b	.L249
.L295:
	.align	2, 0
.L294:
	.word	gText_CommunicationCanceled
.L264:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L296
	cmp	r6, #0
	bne	.L249	@cond_branch
	ldr	r2, .L296+0x4
	b	.L249
.L297:
	.align	2, 0
.L296:
	.word	gText_CantAcceptNewsFromTrainer
	.word	gText_CantAcceptCardFromTrainer
.L267:
	mov	r0, #0x0
	str	r0, [r4]
	ldr	r2, .L298
	b	.L249
.L299:
	.align	2, 0
.L298:
	.word	gText_CommunicationError
.L268:
	mov	r0, #0x1
	str	r0, [r4]
	ldr	r2, .L300
	b	.L249
.L301:
	.align	2, 0
.L300:
	.word	gText_NewTrainerReceived
.L269:
	mov	r0, #0x1
	b	.L273
.L270:
	mov	r0, #0x0
.L273:
	str	r0, [r4]
.L249:
	add	r0, r2, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
.Lfe28:
	.size	 mevent_message,.Lfe28-mevent_message
	.align	2, 0
	.type	 PrintMGSuccessMessage,function
	.thumb_func
PrintMGSuccessMessage:
	push	{r4, r5, r6, lr}
	add	r6, r0, #0
	add	r0, r1, #0
	add	r5, r2, #0
	ldrb	r4, [r6]
	cmp	r4, #0x1
	beq	.L306	@cond_branch
	cmp	r4, #0x1
	bgt	.L312	@cond_branch
	cmp	r4, #0
	beq	.L304	@cond_branch
	b	.L303
.L312:
	cmp	r4, #0x2
	beq	.L308	@cond_branch
	b	.L303
.L304:
	cmp	r0, #0
	beq	.L305	@cond_branch
	bl	AddTextPrinterToWindow1
.L305:
	ldr	r0, .L315
	bl	PlayFanfare
	strh	r4, [r5]
	b	.L314
.L316:
	.align	2, 0
.L315:
	.word	0x155
.L306:
	ldrh	r0, [r5]
	add	r0, r0, #0x1
	strh	r0, [r5]
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	cmp	r0, #0xf0
	bls	.L303	@cond_branch
.L314:
	ldrb	r0, [r6]
	add	r0, r0, #0x1
	strb	r0, [r6]
	b	.L303
.L308:
	bl	IsFanfareTaskInactive
	lsl	r0, r0, #0x18
	cmp	r0, #0
	beq	.L303	@cond_branch
	mov	r0, #0x0
	strb	r0, [r6]
	bl	ClearTextWindow
	mov	r0, #0x1
	b	.L313
.L303:
	mov	r0, #0x0
.L313:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
.Lfe29:
	.size	 PrintMGSuccessMessage,.Lfe29-PrintMGSuccessMessage
	.align	2, 0
	.type	 mevent_message_stamp_card_etc_send_status,function
	.thumb_func
mevent_message_stamp_card_etc_send_status:
	push	{r4, lr}
	add	r3, r0, #0
	ldr	r1, .L337
	mov	r0, #0x0
	str	r0, [r3]
	add	r4, r1, #0
	cmp	r2, #0xe
	bhi	.L318	@cond_branch
	lsl	r0, r2, #0x2
	ldr	r1, .L337+0x4
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L338:
	.align	2, 0
.L337:
	.word	gText_CommunicationError
	.word	.L334
	.align	2, 0
	.align	2, 0
.L334:
	.word	.L319
	.word	.L320
	.word	.L321
	.word	.L322
	.word	.L323
	.word	.L324
	.word	.L325
	.word	.L326
	.word	.L327
	.word	.L328
	.word	.L333
	.word	.L330
	.word	.L331
	.word	.L332
	.word	.L333
.L319:
	ldr	r1, .L339
	b	.L318
.L340:
	.align	2, 0
.L339:
	.word	gText_NothingSentOver
.L320:
	ldr	r1, .L341
	b	.L318
.L342:
	.align	2, 0
.L341:
	.word	gText_RecordUploadedViaWireless
.L321:
	ldr	r1, .L343
	b	.L336
.L344:
	.align	2, 0
.L343:
	.word	gText_WonderCardSentTo
.L322:
	ldr	r1, .L345
.L336:
	mov	r0, #0x1
	str	r0, [r3]
	b	.L318
.L346:
	.align	2, 0
.L345:
	.word	gText_WonderNewsSentTo
.L323:
	ldr	r1, .L347
	b	.L318
.L348:
	.align	2, 0
.L347:
	.word	gText_StampSentTo
.L324:
	ldr	r1, .L349
	b	.L318
.L350:
	.align	2, 0
.L349:
	.word	gText_OtherTrainerHasCard
.L325:
	ldr	r1, .L351
	b	.L318
.L352:
	.align	2, 0
.L351:
	.word	gText_OtherTrainerHasStamp
.L326:
	ldr	r1, .L353
	b	.L318
.L354:
	.align	2, 0
.L353:
	.word	gText_OtherTrainerHasNews
.L327:
	ldr	r1, .L355
	b	.L318
.L356:
	.align	2, 0
.L355:
	.word	gText_NoMoreRoomForStamps
.L328:
	ldr	r1, .L357
	b	.L318
.L358:
	.align	2, 0
.L357:
	.word	gText_OtherTrainerCanceled
.L330:
	add	r1, r4, #0
	b	.L318
.L331:
.L332:
	ldr	r1, .L359
	b	.L318
.L360:
	.align	2, 0
.L359:
	.word	gText_GiftSentTo
.L333:
	ldr	r1, .L361
.L318:
	add	r0, r1, #0
	pop	{r4}
	pop	{r1}
	bx	r1
.L362:
	.align	2, 0
.L361:
	.word	gText_CantSendGiftToTrainer
.Lfe30:
	.size	 mevent_message_stamp_card_etc_send_status,.Lfe30-mevent_message_stamp_card_etc_send_status
	.align	2, 0
	.type	 PrintMGSendStatus,function
	.thumb_func
PrintMGSendStatus:
	push	{r4, r5, lr}
	add	sp, sp, #-0x4
	add	r4, r0, #0
	add	r5, r1, #0
	add	r1, r2, #0
	add	r2, r3, #0
	lsl	r1, r1, #0x18
	lsr	r1, r1, #0x18
	mov	r0, sp
	bl	mevent_message_stamp_card_etc_send_status
	add	r1, r0, #0
	ldr	r0, [sp]
	cmp	r0, #0
	bne	.L364	@cond_branch
	add	r0, r4, #0
	bl	MG_PrintTextOnWindow1AndWaitButton
	b	.L367
.L364:
	add	r0, r4, #0
	add	r2, r5, #0
	bl	PrintMGSuccessMessage
.L367:
	add	sp, sp, #0x4
	pop	{r4, r5}
	pop	{r1}
	bx	r1
.Lfe31:
	.size	 PrintMGSendStatus,.Lfe31-PrintMGSendStatus
	.align	2, 0
	.globl	task_add_00_mystery_gift
	.type	 task_add_00_mystery_gift,function
	.thumb_func
task_add_00_mystery_gift:
	push	{r4, lr}
	ldr	r0, .L369
	mov	r1, #0x0
	bl	CreateTask
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	lsl	r4, r0, #0x2
	add	r4, r4, r0
	lsl	r4, r4, #0x3
	ldr	r0, .L369+0x4
	add	r4, r4, r0
	mov	r0, #0x0
	strb	r0, [r4, #0x8]
	strb	r0, [r4, #0x9]
	strb	r0, [r4, #0xa]
	strb	r0, [r4, #0xb]
	strb	r0, [r4, #0xc]
	strb	r0, [r4, #0xd]
	mov	r1, #0x0
	strh	r0, [r4]
	strh	r0, [r4, #0x2]
	strh	r0, [r4, #0x4]
	strh	r0, [r4, #0x6]
	strb	r1, [r4, #0xe]
	mov	r0, #0x40
	bl	AllocZeroed
	str	r0, [r4, #0x10]
	pop	{r4}
	pop	{r0}
	bx	r0
.L370:
	.align	2, 0
.L369:
	.word	task00_mystery_gift
	.word	gTasks+0x8
.Lfe32:
	.size	 task_add_00_mystery_gift,.Lfe32-task_add_00_mystery_gift
	.align	2, 0
	.globl	task00_mystery_gift
	.type	 task00_mystery_gift,function
	.thumb_func
task00_mystery_gift:
	push	{r4, r5, lr}
	add	sp, sp, #-0x4
	lsl	r0, r0, #0x18
	lsr	r4, r0, #0x18
	lsl	r0, r4, #0x2
	add	r0, r0, r4
	lsl	r0, r0, #0x3
	ldr	r1, .L568
	add	r5, r0, r1
	ldrb	r0, [r5, #0x8]
	cmp	r0, #0x25
	bls	.LCB2572
	b	.L372	@long jump
.LCB2572:
	lsl	r0, r0, #0x2
	ldr	r1, .L568+0x4
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L569:
	.align	2, 0
.L568:
	.word	gTasks+0x8
	.word	.L552
	.align	2, 0
	.align	2, 0
.L552:
	.word	.L373
	.word	.L374
	.word	.L385
	.word	.L390
	.word	.L393
	.word	.L402
	.word	.L414
	.word	.L418
	.word	.L419
	.word	.L428
	.word	.L435
	.word	.L437
	.word	.L446
	.word	.L453
	.word	.L455
	.word	.L458
	.word	.L549
	.word	.L470
	.word	.L472
	.word	.L372
	.word	.L474
	.word	.L484
	.word	.L499
	.word	.L509
	.word	.L516
	.word	.L518
	.word	.L520
	.word	.L522
	.word	.L524
	.word	.L526
	.word	.L533
	.word	.L537
	.word	.L540
	.word	.L542
	.word	.L543
	.word	.L545
	.word	.L549
	.word	.L551
.L373:
	mov	r0, #0x1
	strb	r0, [r5, #0x8]
	b	.L372
.L374:
	add	r0, r5, #0
	add	r0, r0, #0x9
	add	r1, r5, #0
	mov	r2, #0x0
	bl	MysteryGift_HandleThreeOptionMenu
	add	r1, r0, #0
	cmp	r1, #0x1
	beq	.L379	@cond_branch
	cmp	r1, #0x1
	bcc	.L376	@cond_branch
	mov	r0, #0x2
	neg	r0, r0
	cmp	r1, r0
	beq	.L382	@cond_branch
	b	.L372
.L376:
	mov	r0, #0x0
	strb	r0, [r5, #0xc]
	bl	ValidateReceivedWonderCard
	b	.L567
.L379:
	strb	r1, [r5, #0xc]
	bl	ValidateReceivedWonderNews
.L567:
	cmp	r0, #0x1
	bne	.LCB2632
	b	.L554	@long jump
.LCB2632:
	mov	r0, #0x2
	strb	r0, [r5, #0x8]
	b	.L372
.L382:
	mov	r0, #0x25
	strb	r0, [r5, #0x8]
	b	.L372
.L385:
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0
	bne	.L386	@cond_branch
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldr	r1, .L570
	b	.L555
.L571:
	.align	2, 0
.L570:
	.word	gText_DontHaveCardNewOneInput
.L386:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldr	r1, .L572
.L555:
	bl	MG_PrintTextOnWindow1AndWaitButton
	cmp	r0, #0
	bne	.LCB2678
	b	.L372	@long jump
.LCB2678:
	mov	r0, #0x3
	strb	r0, [r5, #0x8]
	mov	r0, #0x0
	mov	r1, #0x1
	bl	PrintMysteryGiftOrEReaderTopMenu
	b	.L372
.L573:
	.align	2, 0
.L572:
	.word	gText_DontHaveNewsNewOneInput
.L390:
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0
	bne	.L391	@cond_branch
	ldr	r0, .L574
	bl	AddTextPrinterToWindow1
	b	.L392
.L575:
	.align	2, 0
.L574:
	.word	gText_WhereShouldCardBeAccessed
.L391:
	ldr	r0, .L576
	bl	AddTextPrinterToWindow1
.L392:
	mov	r0, #0x4
	strb	r0, [r5, #0x8]
	b	.L372
.L577:
	.align	2, 0
.L576:
	.word	gText_WhereShouldNewsBeAccessed
.L393:
	add	r0, r5, #0
	add	r0, r0, #0x9
	add	r1, r5, #0
	mov	r2, #0x1
	bl	MysteryGift_HandleThreeOptionMenu
	add	r4, r0, #0
	cmp	r4, #0x1
	beq	.L396	@cond_branch
	cmp	r4, #0x1
	bcc	.L395	@cond_branch
	mov	r0, #0x2
	neg	r0, r0
	cmp	r4, r0
	beq	.L397	@cond_branch
	b	.L372
.L395:
	bl	ClearTextWindow
	mov	r1, #0x0
	mov	r0, #0x5
	strb	r0, [r5, #0x8]
	strb	r1, [r5, #0xd]
	b	.L372
.L396:
	bl	ClearTextWindow
	mov	r0, #0x5
	strb	r0, [r5, #0x8]
	strb	r4, [r5, #0xd]
	b	.L372
.L397:
	bl	ClearTextWindow
	ldrb	r0, [r5, #0xc]
	bl	ValidateCardOrNews
	cmp	r0, #0
	beq	.LCB2771
	b	.L554	@long jump
.LCB2771:
	strb	r0, [r5, #0x8]
	mov	r0, #0x0
	b	.L556
.L402:
	ldr	r0, .L578
	mov	r1, #0xff
	strb	r1, [r0]
	ldr	r0, .L578+0x4
	strb	r1, [r0]
	ldr	r0, .L578+0x8
	strb	r1, [r0]
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0
	beq	.L404	@cond_branch
	cmp	r0, #0x1
	beq	.L408	@cond_branch
	b	.L403
.L579:
	.align	2, 0
.L578:
	.word	gStringVar1
	.word	gStringVar2
	.word	gStringVar3
.L404:
	ldrb	r0, [r5, #0xd]
	cmp	r0, #0x1
	bne	.L405	@cond_branch
	mov	r0, #0x15
	bl	MEvent_CreateTask_CardOrNewsWithFriend
	b	.L403
.L405:
	cmp	r0, #0
	bne	.L403	@cond_branch
	mov	r0, #0x15
	bl	MEvent_CreateTask_CardOrNewsOverWireless
	b	.L403
.L408:
	ldrb	r0, [r5, #0xd]
	cmp	r0, #0x1
	bne	.L409	@cond_branch
	mov	r0, #0x16
	bl	MEvent_CreateTask_CardOrNewsWithFriend
	b	.L403
.L409:
	cmp	r0, #0
	bne	.L403	@cond_branch
	mov	r0, #0x16
	bl	MEvent_CreateTask_CardOrNewsOverWireless
.L403:
	mov	r0, #0x6
	strb	r0, [r5, #0x8]
	b	.L372
.L414:
	ldr	r0, .L580
	ldrb	r0, [r0]
	cmp	r0, #0
	beq	.L415	@cond_branch
	mov	r0, #0x1
	bl	ClearScreenInBg0
	mov	r0, #0x7
	strb	r0, [r5, #0x8]
	ldrb	r0, [r5, #0xc]
	bl	mevent_client_do_init
	b	.L372
.L581:
	.align	2, 0
.L580:
	.word	gReceivedRemoteLinkPlayers
.L415:
	ldr	r0, .L582
	ldrh	r0, [r0]
	cmp	r0, #0x5
	beq	.LCB2875
	b	.L372	@long jump
.LCB2875:
	mov	r0, #0x1
	bl	ClearScreenInBg0
	b	.L557
.L583:
	.align	2, 0
.L582:
	.word	gSpecialVar_Result
.L418:
	ldr	r0, .L584
	bl	AddTextPrinterToWindow1
	mov	r0, #0x8
	strb	r0, [r5, #0x8]
	b	.L372
.L585:
	.align	2, 0
.L584:
	.word	gText_Communicating
.L419:
	add	r0, r5, #0
	bl	mevent_client_do_exec
	sub	r0, r0, #0x2
	cmp	r0, #0x4
	bls	.LCB2908
	b	.L372	@long jump
.LCB2908:
	lsl	r0, r0, #0x2
	ldr	r1, .L586
	add	r0, r0, r1
	ldr	r0, [r0]
	mov	pc, r0
.L587:
	.align	2, 0
.L586:
	.word	.L426
	.align	2, 0
	.align	2, 0
.L426:
	.word	.L424
	.word	.L423
	.word	.L425
	.word	.L422
	.word	.L421
.L421:
	bl	Rfu_SetCloseLinkCallback
	ldrh	r0, [r5]
	strb	r0, [r5, #0xe]
	mov	r0, #0xd
	strb	r0, [r5, #0x8]
	b	.L372
.L422:
	ldr	r4, [r5, #0x10]
	bl	mevent_client_get_buffer
	add	r1, r0, #0
	add	r0, r4, #0
	mov	r2, #0x40
	bl	memcpy
	bl	mevent_client_inc_flag
	b	.L372
.L423:
	mov	r0, #0xa
	strb	r0, [r5, #0x8]
	b	.L372
.L424:
	mov	r0, #0x9
	strb	r0, [r5, #0x8]
	b	.L372
.L425:
	mov	r0, #0xb
	strb	r0, [r5, #0x8]
	ldr	r0, .L588
	ldr	r1, .L588+0x4
	bl	StringCopy
	b	.L372
.L589:
	.align	2, 0
.L588:
	.word	gStringVar1
	.word	gLinkPlayers+0x8
.L428:
	add	r4, r5, #0
	add	r4, r4, #0x9
	bl	mevent_client_get_buffer
	add	r3, r0, #0
	add	r0, r4, #0
	add	r1, r5, #0
	mov	r2, #0x0
	bl	mevent_message_print_and_prompt_yes_no
	lsl	r0, r0, #0x18
	asr	r1, r0, #0x18
	cmp	r1, #0x1
	beq	.L450	@cond_branch
	cmp	r1, #0x1
	bcs	.L565	@cond_branch
	mov	r0, #0x0
	b	.L558
.L435:
	add	r4, r5, #0
	add	r4, r4, #0x9
	bl	mevent_client_get_buffer
	add	r1, r0, #0
	add	r0, r4, #0
	bl	MG_PrintTextOnWindow1AndWaitButton
	cmp	r0, #0
	bne	.LCB3005
	b	.L372	@long jump
.LCB3005:
	b	.L559
.L437:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldr	r3, .L590
	add	r1, r5, #0
	mov	r2, #0x0
	bl	mevent_message_print_and_prompt_yes_no
	lsl	r0, r0, #0x18
	asr	r1, r0, #0x18
	cmp	r1, #0x1
	beq	.L450	@cond_branch
	cmp	r1, #0x1
	bcs	.L565	@cond_branch
	bl	CheckReceivedGiftFromWonderCard
	cmp	r0, #0x1
	bne	.L440	@cond_branch
	mov	r0, #0xc
	strb	r0, [r5, #0x8]
	b	.L372
.L591:
	.align	2, 0
.L590:
	.word	gText_ThrowAwayWonderCard
.L440:
	mov	r0, #0x0
	b	.L558
.L446:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldr	r3, .L592
	add	r1, r5, #0
	mov	r2, #0x0
	bl	mevent_message_print_and_prompt_yes_no
	lsl	r0, r0, #0x18
	asr	r1, r0, #0x18
	cmp	r1, #0x1
	beq	.L449	@cond_branch
	cmp	r1, #0x1
	bcc	.L448	@cond_branch
.L565:
	mov	r0, #0x1
	neg	r0, r0
	cmp	r1, r0
	beq	.L450	@cond_branch
	b	.L372
.L593:
	.align	2, 0
.L592:
	.word	gText_HaventReceivedCardsGift
.L448:
	mov	r0, #0x0
	b	.L558
.L449:
.L450:
	mov	r0, #0x1
.L558:
	bl	mevent_client_set_param
.L559:
	bl	mevent_client_inc_flag
	mov	r0, #0x7
	strb	r0, [r5, #0x8]
	b	.L372
.L453:
	ldr	r0, .L594
	ldrb	r0, [r0]
	cmp	r0, #0
	beq	.LCB3101
	b	.L372	@long jump
.LCB3101:
	bl	DestroyWirelessStatusIndicatorSprite
	mov	r0, #0xe
	strb	r0, [r5, #0x8]
	b	.L372
.L595:
	.align	2, 0
.L594:
	.word	gReceivedRemoteLinkPlayers
.L455:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldr	r1, .L596
	bl	PrintStringAndWait2Seconds
	cmp	r0, #0
	bne	.LCB3123
	b	.L372	@long jump
.LCB3123:
	ldrb	r0, [r5, #0xd]
	cmp	r0, #0x1
	bne	.L457	@cond_branch
	ldr	r0, .L596+0x4
	ldr	r1, .L596+0x8
	bl	StringCopy
.L457:
	mov	r0, #0xf
	strb	r0, [r5, #0x8]
	b	.L372
.L597:
	.align	2, 0
.L596:
	.word	gText_CommunicationCompleted
	.word	gStringVar1
	.word	gLinkPlayers+0x8
.L458:
	ldrb	r1, [r5, #0xc]
	ldrb	r2, [r5, #0xd]
	ldrb	r3, [r5, #0xe]
	mov	r0, sp
	bl	mevent_message
	add	r1, r0, #0
	cmp	r1, #0
	bne	.L459	@cond_branch
	ldr	r1, [r5, #0x10]
.L459:
	ldr	r0, [sp]
	cmp	r0, #0
	beq	.L460	@cond_branch
	add	r0, r5, #0
	add	r0, r0, #0x9
	add	r2, r5, #0
	bl	PrintMGSuccessMessage
	b	.L560
.L460:
	add	r0, r5, #0
	add	r0, r0, #0x9
	bl	MG_PrintTextOnWindow1AndWaitButton
.L560:
	add	r1, r0, #0
	cmp	r1, #0
	bne	.LCB3188
	b	.L372	@long jump
.LCB3188:
	ldrb	r0, [r5, #0xe]
	cmp	r0, #0x3
	bne	.L463	@cond_branch
	ldrb	r0, [r5, #0xd]
	cmp	r0, #0x1
	bne	.L464	@cond_branch
	mov	r0, #0x1
	bl	GenerateRandomNews
	b	.L463
.L464:
	mov	r0, #0x2
	bl	GenerateRandomNews
.L463:
	ldr	r0, [sp]
	cmp	r0, #0
	beq	.LCB3214
	b	.L561	@long jump
.LCB3214:
	strb	r0, [r5, #0x8]
	mov	r0, #0x0
	b	.L556
.L470:
	add	r0, r5, #0
	add	r0, r0, #0x9
	bl	mevent_save_game
	cmp	r0, #0
	bne	.LCB3233
	b	.L372	@long jump
.LCB3233:
	b	.L554
.L472:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldrb	r1, [r5, #0xc]
	bl	HandleLoadWonderCardOrNews
	cmp	r0, #0
	bne	.LCB3246
	b	.L372	@long jump
.LCB3246:
	b	.L496
.L474:
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0
	bne	.L475	@cond_branch
	ldr	r2, .L598
	ldrh	r1, [r2, #0x2e]
	mov	r0, #0x1
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L476	@cond_branch
	mov	r0, #0x15
	strb	r0, [r5, #0x8]
.L476:
	ldrh	r1, [r2, #0x2e]
	mov	r0, #0x2
	and	r0, r0, r1
	cmp	r0, #0
	bne	.LCB3287
	b	.L372	@long jump
.LCB3287:
	b	.L481
.L599:
	.align	2, 0
.L598:
	.word	gMain
.L475:
	ldr	r0, .L600
	ldrh	r0, [r0, #0x2e]
	bl	MENews_GetInput
	cmp	r0, #0
	beq	.L480	@cond_branch
	cmp	r0, #0x1
	beq	.L481	@cond_branch
	b	.L372
.L601:
	.align	2, 0
.L600:
	.word	gMain
.L480:
	bl	MENews_RemoveScrollIndicatorArrowPair
	b	.L513
.L481:
	mov	r0, #0x1b
	strb	r0, [r5, #0x8]
	b	.L372
.L484:
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0
	bne	.L485	@cond_branch
	bl	WonderCard_Test_Unk_08_6
	cmp	r0, #0
	beq	.L489	@cond_branch
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldrb	r2, [r5, #0xc]
	add	r1, r5, #0
	mov	r3, #0x0
	b	.L562
.L485:
	bl	WonderNews_Test_Unk_02
	cmp	r0, #0
	beq	.L489	@cond_branch
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldrb	r2, [r5, #0xc]
	add	r1, r5, #0
	mov	r3, #0x0
	b	.L562
.L489:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldrb	r2, [r5, #0xc]
	add	r1, r5, #0
	mov	r3, #0x1
.L562:
	bl	HandleMysteryGiftListMenu
	add	r1, r0, #0
	cmp	r1, #0x1
	beq	.L493	@cond_branch
	cmp	r1, #0x1
	bcc	.L492	@cond_branch
	cmp	r1, #0x2
	beq	.L494	@cond_branch
	mov	r0, #0x2
	neg	r0, r0
	cmp	r1, r0
	beq	.L495	@cond_branch
	b	.L372
.L492:
	mov	r0, #0x1c
	strb	r0, [r5, #0x8]
	b	.L372
.L493:
	mov	r0, #0x1d
	strb	r0, [r5, #0x8]
	b	.L372
.L494:
	mov	r0, #0x16
	strb	r0, [r5, #0x8]
	b	.L372
.L495:
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0x1
	bne	.L496	@cond_branch
	bl	MENews_AddScrollIndicatorArrowPair
.L496:
	mov	r0, #0x14
	strb	r0, [r5, #0x8]
	b	.L372
.L499:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldrb	r2, [r5, #0xc]
	add	r1, r5, #0
	bl	mevent_message_prompt_discard
	add	r1, r0, #0
	cmp	r1, #0
	beq	.L501	@cond_branch
	cmp	r1, #0
	ble	.L566	@cond_branch
	cmp	r1, #0x1
	beq	.L513	@cond_branch
	b	.L372
.L501:
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0
	bne	.L511	@cond_branch
	bl	CheckReceivedGiftFromWonderCard
	cmp	r0, #0x1
	bne	.L511	@cond_branch
	mov	r0, #0x17
	strb	r0, [r5, #0x8]
	b	.L372
.L509:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldr	r3, .L602
	add	r1, r5, #0
	mov	r2, #0x1
	bl	mevent_message_print_and_prompt_yes_no
	lsl	r0, r0, #0x18
	asr	r1, r0, #0x18
	cmp	r1, #0x1
	beq	.L512	@cond_branch
	cmp	r1, #0x1
	bcc	.L511	@cond_branch
.L566:
	mov	r0, #0x1
	neg	r0, r0
	cmp	r1, r0
	beq	.L513	@cond_branch
	b	.L372
.L603:
	.align	2, 0
.L602:
	.word	gText_HaventReceivedGiftOkayToDiscard
.L511:
	mov	r0, #0x18
	strb	r0, [r5, #0x8]
	b	.L372
.L512:
.L513:
	mov	r0, #0x15
	strb	r0, [r5, #0x8]
	b	.L372
.L516:
	ldrb	r0, [r5, #0xc]
	mov	r1, #0x1
	bl	TearDownCardOrNews_ReturnToTopMenu
	cmp	r0, #0
	bne	.LCB3511
	b	.L372	@long jump
.LCB3511:
	ldrb	r0, [r5, #0xc]
	bl	DestroyNewsOrCard
	mov	r0, #0x19
	strb	r0, [r5, #0x8]
	b	.L372
.L518:
	add	r0, r5, #0
	add	r0, r0, #0x9
	bl	mevent_save_game
	cmp	r0, #0
	bne	.LCB3527
	b	.L372	@long jump
.LCB3527:
	mov	r0, #0x1a
	strb	r0, [r5, #0x8]
	b	.L372
.L520:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldrb	r1, [r5, #0xc]
	bl	mevent_message_was_thrown_away
	b	.L563
.L522:
	ldrb	r0, [r5, #0xc]
	mov	r1, #0x0
	bl	TearDownCardOrNews_ReturnToTopMenu
	cmp	r0, #0
	bne	.LCB3552
	b	.L372	@long jump
.LCB3552:
	mov	r0, #0x0
	strb	r0, [r5, #0x8]
	b	.L372
.L524:
	ldrb	r0, [r5, #0xc]
	mov	r1, #0x1
	bl	TearDownCardOrNews_ReturnToTopMenu
	cmp	r0, #0
	bne	.LCB3565
	b	.L372	@long jump
.LCB3565:
.L557:
	mov	r0, #0x3
	strb	r0, [r5, #0x8]
	b	.L372
.L526:
	ldrb	r0, [r5, #0xc]
	mov	r1, #0x1
	bl	TearDownCardOrNews_ReturnToTopMenu
	cmp	r0, #0
	bne	.LCB3579
	b	.L372	@long jump
.LCB3579:
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0
	beq	.L529	@cond_branch
	cmp	r0, #0x1
	beq	.L530	@cond_branch
	b	.L528
.L529:
	mov	r0, #0x15
	bl	MEvent_CreateTask_Leader
	b	.L528
.L530:
	mov	r0, #0x16
	bl	MEvent_CreateTask_Leader
.L528:
	mov	r0, #0x1
	strb	r0, [r5, #0xd]
	mov	r0, #0x1e
	strb	r0, [r5, #0x8]
	b	.L372
.L533:
	ldr	r0, .L604
	ldrb	r0, [r0]
	cmp	r0, #0
	beq	.L534	@cond_branch
	mov	r0, #0x1
	bl	ClearScreenInBg0
	mov	r0, #0x1f
	strb	r0, [r5, #0x8]
	b	.L372
.L605:
	.align	2, 0
.L604:
	.word	gReceivedRemoteLinkPlayers
.L534:
	ldr	r0, .L606
	ldrh	r0, [r0]
	cmp	r0, #0x5
	beq	.LCB3632
	b	.L372	@long jump
.LCB3632:
	mov	r0, #0x1
	bl	ClearScreenInBg0
.L554:
	mov	r0, #0x12
	strb	r0, [r5, #0x8]
	b	.L372
.L607:
	.align	2, 0
.L606:
	.word	gSpecialVar_Result
.L537:
	ldr	r0, .L608
	mov	r1, #0xff
	strb	r1, [r0]
	ldr	r0, .L608+0x4
	strb	r1, [r0]
	ldr	r0, .L608+0x8
	strb	r1, [r0]
	ldrb	r0, [r5, #0xc]
	cmp	r0, #0
	bne	.L538	@cond_branch
	ldr	r0, .L608+0xc
	bl	AddTextPrinterToWindow1
	bl	mevent_srv_new_wcard
	b	.L539
.L609:
	.align	2, 0
.L608:
	.word	gStringVar1
	.word	gStringVar2
	.word	gStringVar3
	.word	gText_SendingWonderCard
.L538:
	ldr	r0, .L610
	bl	AddTextPrinterToWindow1
	bl	mevent_srv_init_wnews
.L539:
	mov	r0, #0x20
	strb	r0, [r5, #0x8]
	b	.L372
.L611:
	.align	2, 0
.L610:
	.word	gText_SendingWonderNews
.L540:
	add	r0, r5, #0
	bl	mevent_srv_common_do_exec
	cmp	r0, #0x3
	bne	.L372	@cond_branch
	ldrh	r0, [r5]
	strb	r0, [r5, #0xe]
	mov	r0, #0x21
	strb	r0, [r5, #0x8]
	b	.L372
.L542:
	bl	Rfu_SetCloseLinkCallback
	ldr	r0, .L612
	ldr	r1, .L612+0x4
	bl	StringCopy
	mov	r0, #0x22
	strb	r0, [r5, #0x8]
	b	.L372
.L613:
	.align	2, 0
.L612:
	.word	gStringVar1
	.word	gLinkPlayers+0x24
.L543:
	ldr	r0, .L614
	ldrb	r0, [r0]
	cmp	r0, #0
	bne	.L372	@cond_branch
	bl	DestroyWirelessStatusIndicatorSprite
	mov	r0, #0x23
	strb	r0, [r5, #0x8]
	b	.L372
.L615:
	.align	2, 0
.L614:
	.word	gReceivedRemoteLinkPlayers
.L545:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldrb	r2, [r5, #0xd]
	ldrb	r3, [r5, #0xe]
	add	r1, r5, #0
	bl	PrintMGSendStatus
	cmp	r0, #0
	beq	.L372	@cond_branch
	ldr	r0, [r5, #0xc]
	ldr	r1, .L616
	and	r0, r0, r1
	ldr	r1, .L616+0x4
	cmp	r0, r1
	bne	.L564	@cond_branch
	mov	r0, #0x3
	bl	GenerateRandomNews
.L561:
	mov	r0, #0x11
	strb	r0, [r5, #0x8]
	b	.L372
.L617:
	.align	2, 0
.L616:
	.word	0xffff00
	.word	0x30100
.L549:
	add	r0, r5, #0
	add	r0, r0, #0x9
	ldr	r1, .L618
	bl	MG_PrintTextOnWindow1AndWaitButton
.L563:
	cmp	r0, #0
	beq	.L372	@cond_branch
.L564:
	mov	r0, #0x0
	strb	r0, [r5, #0x8]
.L556:
	mov	r1, #0x0
	bl	PrintMysteryGiftOrEReaderTopMenu
	b	.L372
.L619:
	.align	2, 0
.L618:
	.word	gText_CommunicationError
.L551:
	bl	CloseLink
	ldr	r0, [r5, #0x10]
	bl	Free
	add	r0, r4, #0
	bl	DestroyTask
	ldr	r0, .L620
	bl	SetMainCallback2
.L372:
	add	sp, sp, #0x4
	pop	{r4, r5}
	pop	{r0}
	bx	r0
.L621:
	.align	2, 0
.L620:
	.word	MainCB_FreeAllBuffersAndReturnToInitTitleScreen
.Lfe33:
	.size	 task00_mystery_gift,.Lfe33-task00_mystery_gift
	.align	2, 0
	.globl	GetMysteryGiftBaseBlock
	.type	 GetMysteryGiftBaseBlock,function
	.thumb_func
GetMysteryGiftBaseBlock:
	ldr	r0, .L623
	bx	lr
.L624:
	.align	2, 0
.L623:
	.word	0x1a9
.Lfe34:
	.size	 GetMysteryGiftBaseBlock,.Lfe34-GetMysteryGiftBaseBlock
	.align	2, 0
	.globl	bgid_upload_textbox_1
	.type	 bgid_upload_textbox_1,function
	.thumb_func
bgid_upload_textbox_1:
	push	{lr}
	add	sp, sp, #-0x4
	lsl	r0, r0, #0x18
	lsr	r0, r0, #0x18
	ldr	r1, .L626
	mov	r2, #0x80
	lsl	r2, r2, #0x1
	mov	r3, #0x0
	str	r3, [sp]
	bl	DecompressAndLoadBgGfxUsingHeap
	add	sp, sp, #0x4
	pop	{r0}
	bx	r0
.L627:
	.align	2, 0
.L626:
	.word	gUnkTextboxBorderGfx
.Lfe35:
	.size	 bgid_upload_textbox_1,.Lfe35-bgid_upload_textbox_1
.text
	.align	2, 0

